const key = "globalTypes";
const SHOW_SIDEBAR = `${key}/SHOW_SIDEBAR`;
const HIDE_SIDEBAR = `${key}/HIDE_SIDEBAR`;
const SHOW_FILTER_PANEL = `${key}/SHOW_FILTER_PANEL`;
const HIDE_FILTER_PANEL = `${key}/HIDE_FILTER_PANEL`;

export { SHOW_SIDEBAR, HIDE_SIDEBAR, SHOW_FILTER_PANEL, HIDE_FILTER_PANEL };
